# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mJr
tagline:          Coding Perfectionist
paginate:         1
baseurl:          /
author:
  name:           Mustafa "mJr" Abdel-Tawwab Jr.
  url:            https://twitter.com/mustafajnr
  email:          mustafajnr@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mustafajnr
